Use php included JSON pretty print
Combodo/itop-data-collector-base pull request #10
Opened 2021-03-16 09:49 UTC by Hipska

Note that I added deprecation warning to next version release as this will bump minimal required php version to 5.4.0

2021-03-17 17:42 UTC, piRGoif commented
Seems like a good idea, thanks ! Seems like the \Utils::JSONPrettyPrint method is only used once in Combodo's collectors, but indeed adding a `@deprecated` is a really good idea as this will allow other consumers to migrate !

2021-03-17 17:43 UTC, piRGoif requested changes

2021-03-17 17:43 UTC, piRGoif commented on core/utils.class.inc.php
> +	 * @deprecated 1.3.0
When possible it's nice to explain what to use instead O:)

```suggestion
	 * @deprecated 1.3.0 use `json_encode($json, JSON_PRETTY_PRINT);` instead
```

2021-03-17 20:26 UTC, Hipska commented
@piRGoif What about replacing the content of the deprecated method with a php native code?

2021-03-18 09:01 UTC, piRGoif approved these changes

2021-03-18 09:03 UTC, Hipska commented
And maybe also a log warning message?

2021-03-18 09:03 UTC, piRGoif commented
Thanks for the deprecated message change !

About changing \Utils::JSONPrettyPrint, I would advise against it as this may introduce behavior change : both codes (Combodo's and PHP) might not produce the same result...
Having a transition period will allow to fallback to the old method if needed.

I'm setting this PR to be reviewed by the dev team !

2021-03-18 09:05 UTC, Hipska commented
Good point, but I would still add a log message if this method is still used. Agree?

2021-03-18 09:06 UTC, piRGoif commented
> And maybe also a log warning message?

Yes seems like a good idea.
I have an ungoing proposition about logging deprecated calls (Combodo/iTop#193) but it won't apply here as this would introduce dependency to the iTop version where this will be introduced (probably 3.0.0).
So a trigger_error maybe ? We'll have to talk about this with the dev team !

2021-03-18 09:34 UTC, Hipska commented
Oh yeah, I was just thinking about a simple `Utils::Log` message.

2021-03-18 09:39 UTC, piRGoif commented
>> a trigger_error maybe ?
> Oh yeah, I was just thinking about a simple `Utils::Log` message.

That is an option too indeed, and less "violent". Well noted !

2021-03-18 16:09 UTC, piRGoif approved these changes
It was a good idea to add a notice example. Again, the final solution will be chosed by the dev team
I'm approving the code as is for now, and we'll see what the dev team discussion brings to the table :)

2021-04-02 13:30 UTC, piRGoif commented
Ref for `JSON_PRETTY_PRINT` flag availability : https://www.php.net/manual/fr/json.constants.php#constant.json-pretty-print

2021-05-28 09:35 UTC, piRGoif requested changes
Just reviewing this PR before showing it to the dev team, I think adding the PHP requirement in the phpdoc would be a good idea

2021-05-28 09:35 UTC, piRGoif commented on core/utils.class.inc.php
> +	 * @deprecated 1.3.0 use `json_encode($value, JSON_PRETTY_PRINT);` instead
```suggestion
	 * @deprecated 1.3.0 use `json_encode($value, JSON_PRETTY_PRINT);` instead (PHP 5.4.0 required)
```

2021-05-28 09:42 UTC, piRGoif approved these changes
Thanks !

2021-05-28 15:48 UTC, piRGoif commented on toolkit/dump_tasks.php
> +				echo json_encode($aCurrentTaskDefinition, JSON_PRETTY_PRINT);
```suggestion
				if (defined('JSON_PRETTY_PRINT') {
					echo json_encode($aCurrentTaskDefinition, JSON_PRETTY_PRINT);
				} else {
					echo Utils::JSONPrettyPrint($sDefinition)."\n";
				}
```

2021-05-28 15:56 UTC, piRGoif commented
Thanks, merging !

2021-05-28 15:58 UTC, merged

2021-09-10 14:09 UTC, Hipska commented
FYI, i don't think there is still the need to check if the pretty print exists as the collector requires 5.6 minimal by default..

2021-09-14 08:14 UTC, piRGoif commented
Thanks for this remark
I'm not sure the collector does a good job checking for PHP Version ? 
This would take some time to check, I'm not sure this is worse the effort ?

2021-09-14 08:42 UTC, Hipska commented
The problem is more that the json/csv/sql collectors are loaded/included always. And they set their own php version requirement, even when they are not used. The command used is just `phpversion()`, so I don't think that's giving a impact.

The `Orchestrator::AddCollector` could call a method on the class like `Collector::GetRequirementList` maybe?