Feature/collectionplan enhancement
Combodo/itop-data-collector-base pull request #20
Opened 2022-12-26 10:39 UTC by xtophe38

This PR improves the Collector:CheckToLaunch method.

It provides to the collector that needs to check if it can be launched or not, the list of collectors already orchestrated. With this information, it can check its dependencies with other classes and possibly deny the launch if some classes are missing from the collection plan.

2023-01-01 22:53 UTC, odain-cbd approved these changes

2023-01-02 17:17 UTC, Molkobain requested changes

2023-01-02 17:17 UTC, Molkobain commented on core/collector.class.inc.php
> +    public function CheckToLaunch($aOrchestratedCollectors): bool {
```suggestion
    public function CheckToLaunch(array $aOrchestratedCollectors): bool {
```

Also please document the param type and structure in the PHPDoc. See https://blog.jetbrains.com/phpstorm/2022/02/phpstorm-2022-1-eap-3/#multiline_and_nested_array_shapes

2023-01-02 17:17 UTC, Molkobain commented on test/CollectionPlanTest.php
> +	public function setUp():void
```suggestion
	public function setUp(): void
```

2023-01-02 17:17 UTC, Molkobain commented on test/CollectionPlanTest.php
> +	public function tearDown():void
```suggestion
	public function tearDown(): void
```

2023-01-02 17:17 UTC, Molkobain commented on test/collectionplan/collectors_files/LegacyCollector.class.inc.php
> +	public function CheckToLaunch($aOrchestratedCollectors): bool
```suggestion
	/**
	 * @inheritDoc
	 */
	public function CheckToLaunch(array $aOrchestratedCollectors): bool
```

2023-01-02 17:17 UTC, Molkobain commented on core/collector.class.inc.php
> +    public function CheckToLaunch($aOrchestratedCollectors): bool {
Has any collector using this new collection plan method been released yet?

2023-01-02 17:17 UTC, Molkobain commented
Please update the PR title with the corresponding bug title (eg. "N°1234 - Something new")

2023-01-03 13:20 UTC, xtophe38 commented
> Please update the PR title with the corresponding bug title (eg. "N°1234 - Something new")

Done

2023-01-03 15:28 UTC, Molkobain approved these changes

2023-01-09 09:23 UTC, Hipska approved these changes

2023-01-10 15:48 UTC, piRGoif commented
Accepted during functional review

We will need to do lots of tests :) 
And also a big work will need to be done on the collector base documentation

@xtophe38 can you merge the PR ?

2023-01-10 17:40 UTC, merged