Allow login_mode to be set
Combodo/itop-data-collector-base pull request #8
Opened 2020-12-03 11:05 UTC by Hipska

In the case where the first `allowed_login_types` is for example `saml`, then the calls to the API will be redirected to the SAML identity provider, but this is not supported by the curl calls.

Solution is to put `login_mode=form` as an extra URL parameter. I have made it configurable in case of any other situation that is not using form by default.

2020-12-10 08:47 UTC, piRGoif approved these changes

2020-12-10 08:47 UTC, piRGoif commented
Thanks for this !
As a reference, login_mode parameter is documented here : https://www.itophub.io/wiki/page?id=2_2_0%3Aadmin%3Auser_authentication_options#login_mode_page_parameter

2020-12-15 17:26 UTC, piRGoif commented
Hello, 
After a team review we would like to keep this optional : so that by default no parameter would be added to the URL, and only if the config parameter is present then add the parameter in the URL.

2020-12-17 13:26 UTC, Hipska commented
That makes sense indeed. I will have a look.

2020-12-17 14:52 UTC, piRGoif requested changes
Thanks for the quick modification !
But I would ask a little form change : add the braces for the if, even they are on one line ?

2020-12-17 14:52 UTC, piRGoif commented on core/collector.class.inc.php
> +			if (!empty($sLoginMode)) $sUrl .= '?login_mode=' . $sLoginMode;
```suggestion
			if (!empty($sLoginMode)) { $sUrl .= '?login_mode=' . $sLoginMode;}
```

2020-12-17 14:52 UTC, piRGoif commented on core/collector.class.inc.php
> +		if (!empty($sLoginMode)) $sUrl .= '?login_mode=' . $sLoginMode;
```suggestion
		if (!empty($sLoginMode)) { $sUrl .= '?login_mode=' . $sLoginMode;}
```

2020-12-17 14:52 UTC, piRGoif commented on core/restclient.class.inc.php
> +		if (!empty($sLoginMode)) $sUrl .= '&login_mode=' . $sLoginMode;
```suggestion
		if (!empty($sLoginMode)) { $sUrl .= '&login_mode=' . $sLoginMode;}
```

2020-12-17 15:00 UTC, Hipska commented
Does this module follow other coding convention than iTop? As it is allowed to have a single line `if` without braces over there, and it is used a lot in the current codebase.

2020-12-17 15:26 UTC, piRGoif commented
Indeed, the [coding standards](https://www.itophub.io/wiki/page?id=latest%3Acustomization%3Acoding_standards) page doesn't tell a word about this, and in the existing codebase, either iTop or iTop modules, there are a lot of such if without braces. Lots of this legacy code was developed using simple text editors, limited formatting rules... 

We tend to change this step by step since some years now, but we can't refactor the whole codebase as this would make the history harder to read (especially the blame function in large and old files like MetaModel or such)
For example our iTop .editorconfig has some rules on enforcing braces, like [this one for PHP](https://github.com/Combodo/iTop/blob/develop/.editorconfig#L347). 

This is a good practice as avoiding them could cause great confusions, like adding a line after the if thinking it would be part of it... and it's not !
Adding braces doesn't cost much, so :)

2020-12-17 15:40 UTC, piRGoif approved these changes

2020-12-17 15:40 UTC, piRGoif commented
Thanks, I'm merging this PR !

2020-12-17 15:43 UTC, merged

2020-12-18 17:18 UTC, piRGoif commented
After some discussions with @dflaven, @etaloc and of course @Hipska we decided to hardcode the login_mode.
See ed04f2d1

2020-12-19 11:00 UTC, piRGoif commented
Combodo internal ref : N°3559